line-length = 80

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"gendiff/formatters/stylish.py" = ["E501"]
"gendiff/tree.py"               = ["E501"]

[lint]
preview = true
select = ["E", "F", "I", "C90"]
