name: Python CI

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Быстрая установка uv (≈ 0.5 с)  :contentReference[oaicite:2]{index=2}
      - uses: astral-sh/setup-uv@v6

      # ── virtualenv + deps ──────────────────────────────────
      - name: Create venv and install dev-deps
        run: |
          uv venv .venv                      # создаём venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      # ── линтер + тесты ────────────────────────────────────
      - name: Ruff + Pytest
        run: |
          source .venv/bin/activate
          make check                         # ruff + pytest

      # ── отчёт покрытия (coverage.xml) ─────────────────────
      - name: Coverage
        run: |
          source .venv/bin/activate
          make test-coverage
