name: ci
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install project + dev-deps
        run: |
          pip install uv
          uv pip install -e ".[dev]"

      - name: Lint
        run: make lint

      - name: Tests + coverage
        run: make coverage
