name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install project + dev-deps
        run: |
          pip install uv
          uv pip install -e ".[dev]"

      - name: Lint + pytest
        run: make check          # «check» → ruff + pytest

      # генерируем coverage.xml, чтобы Sonar мог его забрать при нужде
      - name: Coverage
        run: make test-coverage
