name: Python CI

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # готовая утилита от Astral — ставит uv во /usr/local/bin
      - uses: astral-sh/setup-uv@v6

      # ─── виртуальная среда + зависимости ─────────────────────
      - name: Create venv and install dev-deps
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      # ─── линтер + pytest ─────────────────────────────────────
      - name: Lint & tests
        run: |
          source .venv/bin/activate
          make check

      # ─── отчёт покрытия (xml) ───────────────────────────────
      - name: Coverage
        run: |
          source .venv/bin/activate
          make test-coverage
