name: sonar

on:
  push:
    branches: [main]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install deps + run tests (coverage)
        run: |
          pip install uv
          uv pip install -e ".[dev]"
          make test-coverage          # создаёт coverage.xml

      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@v2   # ← исправлено
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=sssspoddub_python-project-50
            -Dsonar.organization=sssspoddub
            -Dsonar.python.coverage.reportPaths=coverage.xml
