name: sonar

on:
  push:
    branches: [main]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dev-dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[dev]"

      - name: Run tests & generate coverage.xml
        run: |
          python -m pytest --cov=gendiff --cov-report=xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2   # правильный owner + repo
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=sssspoddub_python-project-50
            -Dsonar.organization=sssspoddub
            -Dsonar.python.coverage.reportPaths=coverage.xml
