name: sonar

on:
  push:
    branches: [main]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6          # тот же шаг установки uv

      - name: Create venv & install dev-deps
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Run tests (create coverage.xml)
        run: |
          source .venv/bin/activate
          uv run pytest --cov=gendiff --cov-report=xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=sssspoddub_python-project-50
            -Dsonar.organization=sssspoddub
            -Dsonar.python.coverage.reportPaths=coverage.xml
